export const USUARIO_SERVICE = 'USUARIO_SERVICE';
export const PRODUCTO_SERVICE = 'PRODUCTO_SERVICE';
export const COMPRAS_CABECERA_SERVICE = 'COMPRAS_CABECERA_SERVICE';
export const NATS_SERVICE = 'NATS_SERVICE';